

package koala.dynamicjava.tree.visitor;

import koala.dynamicjava.tree.*;
import koala.dynamicjava.tree.tiger.GenericReferenceTypeName;
import koala.dynamicjava.tree.tiger.HookTypeName;



public interface Visitor<T> {
  T visit(CompilationUnit node);
  T visit(PackageDeclaration node);
  T visit(ImportDeclaration node);
  T visit(EmptyStatement node);
  T visit(ExpressionStatement node);
  T visit(WhileStatement node);
  T visit(ForStatement node);
  T visit(ForEachStatement node);
  T visit(DoStatement node);
  T visit(SwitchStatement node);
  T visit(SwitchBlock node);
  T visit(LabeledStatement node);
  T visit(BreakStatement node);
  T visit(TryStatement node);
  T visit(CatchStatement node);
  T visit(ThrowStatement node);
  T visit(ReturnStatement node);
  T visit(SynchronizedStatement node);
  T visit(ContinueStatement node);
  T visit(IfThenStatement node);
  T visit(IfThenElseStatement node);
  T visit(AssertStatement node);
  T visit(Literal node);
  T visit(ThisExpression node);
  T visit(AmbiguousName node);
  T visit(VariableAccess node);
  T visit(SimpleFieldAccess node);
  T visit(ObjectFieldAccess node);
  T visit(StaticFieldAccess node);
  T visit(SuperFieldAccess node);
  T visit(ArrayAccess node);
  T visit(ObjectMethodCall node);
  T visit(SimpleMethodCall node);
  T visit(StaticMethodCall node);
  T visit(ConstructorCall node);
  T visit(SuperMethodCall node);
  T visit(BooleanTypeName node);
  T visit(ByteTypeName node);
  T visit(ShortTypeName node);
  T visit(CharTypeName node);
  T visit(IntTypeName node);
  T visit(LongTypeName node);
  T visit(FloatTypeName node);
  T visit(DoubleTypeName node);
  T visit(VoidTypeName node);
  T visit(ReferenceTypeName node);
  T visit(GenericReferenceTypeName node);
  T visit(ArrayTypeName node);
  T visit(HookTypeName node);
  T visit(TypeExpression node);
  T visit(PostIncrement node);
  T visit(PostDecrement node);
  T visit(PreIncrement node);
  T visit(PreDecrement node);
  T visit(ArrayInitializer node);
  T visit(ArrayAllocation node);
  T visit(SimpleAllocation node);
  T visit(AnonymousAllocation node);
  T visit(InnerAllocation node);
  T visit(AnonymousInnerAllocation node);
  T visit(CastExpression node);
  T visit(NotExpression node);
  T visit(ComplementExpression node);
  T visit(PlusExpression node);
  T visit(MinusExpression node);
  T visit(MultiplyExpression node);
  T visit(DivideExpression node);
  T visit(RemainderExpression node);
  T visit(AddExpression node);
  T visit(SubtractExpression node);
  T visit(ShiftLeftExpression node);
  T visit(ShiftRightExpression node);
  T visit(UnsignedShiftRightExpression node);
  T visit(LessExpression node);
  T visit(GreaterExpression node);
  T visit(LessOrEqualExpression node);
  T visit(GreaterOrEqualExpression node);
  T visit(InstanceOfExpression node);
  T visit(EqualExpression node);
  T visit(NotEqualExpression node);
  T visit(BitAndExpression node);
  T visit(ExclusiveOrExpression node);
  T visit(BitOrExpression node);
  T visit(AndExpression node);
  T visit(OrExpression node);
  T visit(ConditionalExpression node);
  T visit(SimpleAssignExpression node);
  T visit(MultiplyAssignExpression node);
  T visit(DivideAssignExpression node);
  T visit(RemainderAssignExpression node);
  T visit(AddAssignExpression node);
  T visit(SubtractAssignExpression node);
  T visit(ShiftLeftAssignExpression node);
  T visit(ShiftRightAssignExpression node);
  T visit(UnsignedShiftRightAssignExpression node);
  T visit(BitAndAssignExpression node);
  T visit(ExclusiveOrAssignExpression node);
  T visit(BitOrAssignExpression node);
  T visit(BlockStatement node);
  T visit(ClassDeclaration node);
  T visit(InterfaceDeclaration node);
  T visit(ConstructorDeclaration node);
  T visit(MethodDeclaration node);
  T visit(FormalParameter node);
  T visit(FieldDeclaration node);
  T visit(VariableDeclaration node);
  T visit(EnumDeclaration.EnumConstant node);
  T visit(ClassInitializer node);
  T visit(InstanceInitializer node);
  T visit(ModifierSet node);
  T visit(Annotation node);
}
